# Generated by Django 4.2.7 on 2023-11-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('hostname', models.CharField(blank=True, max_length=200)),
                ('article_date', models.DateField(null=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('markdown_content', models.TextField(blank=True)),
                ('json_parse_result', models.JSONField(null=True)),
                ('header_image_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
