# Generated by Django 5.0 on 2024-02-07 02:07

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='content_search',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', 'excerpt', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('raw_text_content', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField(blank=True)),
        ),
    ]
