# Generated by Django 4.2.7 on 2023-11-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_viewed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
