# Generated by Django 5.0 on 2023-12-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0003_backfill_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='lynx_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
