# Generated by Django 5.0.2 on 2024-02-19 04:56

import django.contrib.postgres.search
from django.db import migrations, models


def refresh_all_notes_content_search(apps, schema_editor):
  Note = apps.get_model('lynx', 'Note')
  for note in Note.objects.all():
    note.save()


class Migration(migrations.Migration):

  dependencies = [
      ('lynx', '0004_alter_link_managers'),
  ]

  operations = [
      migrations.AddField(
          model_name='note',
          name='content_search',
          field=models.GeneratedField(
              db_persist=True,
              expression=django.contrib.postgres.search.CombinedSearchVector(
                  django.contrib.postgres.search.SearchVector('content',
                                                              config='english',
                                                              weight='A'),
                  '||',
                  django.contrib.postgres.search.SearchVector('link_title',
                                                              config='english',
                                                              weight='B'),
                  django.contrib.postgres.search.SearchConfig('english')),
              output_field=django.contrib.postgres.search.SearchVectorField()),
      ),
      # The new field is only persisted on save so we need to refresh all notes.
      # It's not necessary to do this when unapplying the migration since the column will be dropped.
      migrations.RunPython(
          refresh_all_notes_content_search,
          migrations.RunPython.noop,
      )
  ]
