# Generated by Django 5.0.2 on 2024-02-22 02:41

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0005_note_content_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'base_manager_name': 'objects', 'ordering': ['-added_at']},
        ),
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('objects_with_full_content', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
