# Generated by Django 5.0.2 on 2024-02-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0006_alter_link_options_alter_link_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkupload',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creator',
            new_name='user',
        ),
    ]
