# Generated by Django 5.0 on 2023-12-21 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0006_usercookie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_fetched_at', models.DateTimeField(null=True)),
                ('etag', models.CharField(blank=True, max_length=1000)),
                ('modified', models.CharField(blank=True, max_length=1000)),
                ('feed_url', models.URLField(max_length=2000)),
                ('feed_name', models.CharField(max_length=1000)),
                ('feed_description', models.TextField(blank=True)),
                ('feed_image_url', models.URLField(blank=True, max_length=2000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='created_from_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lynx.feed'),
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(null=True)),
                ('guid', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(max_length=2000)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lynx.feed')),
                ('saved_as_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lynx.link')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('feed', 'guid')},
            },
        ),
    ]
