# Generated by Django 5.0 on 2024-01-01 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0008_alter_link_created_from_feed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='link',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
