# Generated by Django 5.0.2 on 2024-04-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0008_linkarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='summarization_model',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-3.5-turbo-0125', 'gpt-3.5-turbo-0125'), ('gpt-4', 'gpt-4'), ('gpt-4-turbo-preview', 'gpt-4-turbo-preview'), ('claude-3-haiku-20240307', 'claude-3-haiku-20240307'), ('claude-3-sonnet-20240229', 'claude-3-sonnet-20240229'), ('claude-3-opus-20240229', 'claude-3-opus-20240229')], default='gpt-3.5-turbo', max_length=255),
        ),
    ]
