# Generated by Django 5.0 on 2024-01-01 02:52
from django.db import migrations


def set_added_at_to_created_at(apps, schema_editor):
  Link = apps.get_model('lynx', 'Link')
  for link in Link.objects.all():
    link.added_at = link.created_at
    link.save()

# Not strictly idempotent or undoable, but we don't really care about it.
def reverse(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0009_alter_link_options_link_added_at'),
    ]

    operations = [
      migrations.RunPython(set_added_at_to_created_at, reverse_code=reverse),
    ]
