# Generated by Django 5.0 on 2024-01-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0011_bulkupload_link_created_from_bulk_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='lynx.feed'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='saved_as_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_feed_item', related_query_name='created_from_feed_item', to='lynx.link'),
        ),
    ]
