# Generated by Django 5.0 on 2024-01-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0012_alter_feeditem_feed_alter_feeditem_saved_as_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='headers_for_scraping',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='headers_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
