# Generated by Django 5.0 on 2024-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0013_usersetting_headers_for_scraping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='auto_add_feed_items_to_library',
            field=models.BooleanField(default=False),
        ),
    ]
