# Generated by Django 5.0 on 2024-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0015_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='link_title',
            field=models.TextField(blank=True),
        ),
    ]
